### ISSUE TITLE
NodeSchool Oakland July 18th @ NPM

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#12]
Howdy everyone, this is just an official thread about the next NodeSchool Oakland event, continued from https://github.com/nodeschool/oakland/issues/8. Every future event will have an issue like this once it is confirmed.

The event will be on **July 18th, from 1-6PM, at NPM**. NPM is at 200 Frank H. Ogawa Plaza, 5th Floor in Oakland.

Stealing blatantly from @jedireza over at [NodeSchool SF](https://github.com/nodeschool/sanfrancisco/issues/80), I felt it would be a good idea to confirm some mentors for the upcoming event:

- [x] @paulgrock 
- [x] @wfro
- [x] @jedireza 
- [ ] @llkats
- [x] @isaacs
- [ ] @smallhaxe
- [ ] @jessepollak
- [ ] @frijol

...and perhaps some of the fine folks from npm? 

Organizers:

- [x] @fauntleroy

If you or someone you know wants to get involved in mentoring or organizing this meetup, speak up in this issue!

**Comment by jedireza** [comment]
It would be a pleasure to help out. Count me in!

**Comment by paulgrock** [comment]
I'm down to mentor or help in someway if you still need people.

**Comment by mikeal** [comment]
I'm gonna be moving this weekend so I'm out :(

**Comment by wfro** [comment]
In for mentoring!

**Comment by Fauntleroy** [comment]
@jedireza @paulgrock @wfro Awesome! Drop on by!

**Comment by smallhaxe** [comment]
Likewise, count me in :) Thanks for the push toward relaunch!

**Comment by GrahamGIGA** [comment]
The tickets don't have a time on them.  Will you be emailing attendees with logistics?

I was surprised it was an afternoon only.

Cheers

**Comment by Fauntleroy** [comment]
@GrahamGIGA The time is listed in two places: on the website proper, and at the top of the ti.to event page in the description. This really isn't ideal, however, and it can be easily missed.

@jedireza @llkats how do y'all at NodeSchool SF handle showing times for ti.to events? Setting the date is easy, but there's no way to set a date.When I checked their documentation, they suggested adding the time to the event's description field.

**Comment by llkats** [comment]
We've had this point of confusion in the past too. For International Day, I ended up adding the time in the Additional Information field: https://ti.to/nodeschoolsf/international-day-may-23rd/. I think that for people who happen to miss the times on the ti.to page and the event homepage, answering github issues/emails/tweets will have have to suffice. ¯\_(ツ)_/¯

I let @Fauntleroy know this already, but I am unable to attend the event this Saturday. Hope to make it to an Oakland Nodeschool in the future! Have a great time!

**Comment by Fauntleroy** [comment]
Thanks to all our wonderful mentors for coming out and helping yesterday! The event went super smoothly and many a learners were helped due to your hard work!

@jedireza @isaacs If I have missed any mentors in the list above, please let me know (so I can properly credit them, and call out to them in the future!)

On to the next event!
