### ISSUE TITLE
NodeSchool Oakland August 15th @ Sparkart

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#13]
### Event Details

Hey everyone, it's that time again! :tada: 

I just got confirmation from @monika at [Sparkart](http://www.sparkart.com) that we're good to go for an August workshopper event. Here are the details:

August 15th, 1-5PM
[Sparkart Inc](https://www.google.com/maps/place/Sparkart+Inc./@37.8111343,-122.2673623,17z/data=!3m1!4b1!4m2!3m1!1s0x808f80b3006df78b:0xb54689dafe100759)
[2201 Broadway #100](https://www.google.com/maps/place/Sparkart+Inc./@37.8111343,-122.2673623,17z/data=!3m1!4b1!4m2!3m1!1s0x808f80b3006df78b:0xb54689dafe100759)
[Oakland, CA 94612](https://www.google.com/maps/place/Sparkart+Inc./@37.8111343,-122.2673623,17z/data=!3m1!4b1!4m2!3m1!1s0x808f80b3006df78b:0xb54689dafe100759)

### Mentors and Volunteers

As always we'll need some mentors to drop by and help people move through the lessons. If you or anyone you know would like to mentor, please leave a comment in this issue.

Here's a list of potential mentors I'm aware of:
- [ ] @isaacs
- [ ] @mikeal 
- [ ] @frijol
- [ ] @smallhaxe
- [ ] @wfro
- [ ] you?
- [ ] you?
- [ ] you?

Organizers:
- [x] @fauntleroy

Sparkart:
- [x] @monika

### Transit details

According to Google, Sparkart is a short 6 minute walk from the 19th Street BART station in uptown Oakland.

I haven't driven in the Oakland area for a while, so if anyone has any recommendations on where/how to park in the area, please speak up!

### Greeting checklist

When mentees arrive at the event, I'd like someone to greet them (ideally me or one of the volunteers if I'm busy). There are a few basic things that each mentee should be told when they arrive:

- Where to go ("find a seat there, there, or there!")
- What to do if they need help ("raise your hand(s?) up in the air!")
- That photographs of the event will be taken, and that they can opt out of being in photos
- If they have any special dietary needs (if they are vegetarian, vegan, gluten-free, etc)
- Where the bathrooms are (this could be complicated, actually)

-----

As always, I'm extremely grateful to the volunteers that make this event happen. Y'all the best :+1:

**Comment by jedireza** [comment]
I'll be out of town that weekend.

**Comment by paulgrock** [comment]
Unfortunately I'm out of town that weekend as well.

**Comment by llkats** [comment]
Ack, will also be out of town at the Andconf coding retreat. Please let me know if you need help getting the word out for other mentors.

**Comment by Fauntleroy** [comment]
@llkats @jedireza @paulgrock If you've got any East Bay mentors in mind, please direct them here! I feel like we might be short, especially if others are also busy that weekend.

**Comment by Fauntleroy** [comment]
Since I haven't yet announced the event, and since http://cyber.wizard.institute/ goes until the 15th, I'm considering moving the event back a day and doing this on Sunday, August 16th from 1-5PM.

**Comment by upekabee** [comment]
I'm slammed in August and can't make this event. I should be freerer in September/October, please let me know for the next one. Thanks :)

**Comment by smallhaxe** [comment]
I'll be out of town that weekend-- sad to have to miss this one.  I'll encourage others to mentor, though!

**Comment by Fauntleroy** [comment]
I unfortunately haven't had any mentors step forward for this event, so please make sure you reach out!
