### ISSUE TITLE
Oakland chapter logo

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#14]
Thanks to the efforts of the talented Savio Alphonso (https://dribbble.com/savioa777) and @feesh NodeSchool Oak has a schnazzy new hexagon logo!

![ns oak yellow 2x](https://cloud.githubusercontent.com/assets/507047/10340027/079e476a-6cc3-11e5-9e73-205e95841fa8.png)

Provided there are no objections, I'll be printing this off on some stickers for our next event (hopefully next month)!

**Comment by jedireza** [comment]
:+1:

**Comment by smallhaxe** [comment]
Nice!
