### ISSUE TITLE
November Event

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#15]
Hey everyone! I know it's been a while, but I'd like to plan out the next event for NodeSchool Oakland! Here are a few things that are going on related to the next event:

- I've talked to @isaacs and determined that the new NPM offices are a possible venue! There are some complications around air conditioning/lights being on after office hours, but they're nothing that we can't surmount. I need to drop by the space sometime soon and get some more detailed information about it, but from what I've heard it would be an ideal location for a large number of nodeschoolers. With any luck it can become a regular location for NodeSchool events—just like Mozilla has been for NodeSchool SF.
- @jedireza has expressed interest in creating some sort of joint NodeSchool SF / Oakland events for the November/December months, where both groups have a single event at one location. One event would be held in Oakland, and the other event would be in SF.
- Thanksgiving falls on the 26th of November this year. This means that the ideal Saturdays for a NodeSchool event are the 14th and 21st. Are there any big events going on those days? Would you be available?

Speak up if you have any ideas about the next event/future events! Let's get regular, monthly NS Oak events going!

**Comment by smallhaxe** [comment]
It'd be great to have a regular host here in Oakland. (Proactive/hopeful thank you, @isaacs + co.)

I favor the @jedireza idea to consolidate and alternate between Oak + SF through November + December, as I won't be able to fit four weekend events in over those two months. However, looking forward to the new year, it would be nice to get into a rhythm of two events per month between the two chapters (second and last Saturdays?).

+1 for 21 Nov (NPM?)
+1 for 12 Dec (Mozilla?)

Thanks, @fauntleroy, for getting the ball rolling!

**Comment by yogipatelsf** [comment]
Would have loved to go to the meeting in SF this weekend but I have a friend's kid's b-day party to attend.  I am open on either 14th or 21st.  I am a beginner to program but I hope thats okay.  Heard a lot of good things about Node.

www.linkedin.com/in/yogipatel

**Comment by jedireza** [comment]
:+1: for a November event in Oakland.

I will be out of town for most of November and December. So we'll need to find another Mozillian that's willing to be a host in December in order to use the Mozilla SF space.

**Comment by llkats** [comment]
I can mentor on the 14th or the 21st. If the space isn't ready for either of those days due to climate control concerns, we should run up the flag really, really soon to find an alternate location.

I kind of like the idea of hosting an either/or meetup every now and then. It'd help shake things up a bit, and establish more of an Oakland-SF partnership. What if we thought about holding both events one month, and then trading off every other month with a lot of cross-posting and social media advertising? Another thing to prioritize is training up more people into mentorship roles, so that we have a deep mentor pool to draw from and no one gets fatigued from volunteering too much.

**Comment by jedireza** [comment]
I'm able to help mentor on the 14th.

:beers: SF <=> OAK :beers:

**Comment by isurfbecause** [comment]
I am able to mentor on Nov 14 :+1:

**Comment by ajfarkas** [comment]
Would love to mentor, either weekend. 🎓

**Comment by paulgrock** [comment]
I can't make the 14th but if the 21st is still on the table I can be there that weekend.

**Comment by noffle** [comment]
I'd be happy to mentor on the 14th.

**Comment by LizzHale** [comment]
First time mentor here --- I'd love to help out either weekend (prefer the 14th though).

**Comment by Fauntleroy** [comment]
Hey everyone, I've just gotten confirmation from npm that **Saturday, November 14th** is a good time! Here's what needs to get done:

- [ ] Determine time (1pm - 5pm?)
- [ ] Update NodeSchool Oakland website
- [ ] Create ti.to event
- [ ] Create mentor registration issue
- [ ] Scope out npm space and determine things like max # of participants, wifi setup, best place to put pizza, snack situation
- [ ] Promote event (after ti.to event / website)
