### ISSUE TITLE
Mentor Registration for November 14th @ npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#16]
We've got an impending event on the **14th of November from 1-5PM at [npm](https://www.npmjs.com/)**! This will be our first combined SF & OAK event, and I'm :sparkles:RIDICULOUSLY EXCITED:sparkles: about it!

If you'd like to be a mentor at this event, please speak up in this thread!

Here's a list of our lovely mentors & volunteers (# of mentor slots may change once I get more information on npm's capacity):

#### Mentors

- [x] @llkats
- [x] @isurfbecause
- [x] @ajfarkas
- [x] @noffle
- [x] @LizzHale 
- [x] @isaacs
- [x] @LindsayElia
- [x] @smallhaxe
- [x] @upekabee 
- [x] @bengl
- [x] @negomi
- [x] @substack 
- [x] @Shinobi881 

#### Organizers

- [x] @fauntleroy

#### Some guy

- [x] @jedireza 

As always, thanks to everyone who's willing to volunteer their time!

**Comment by llkats** [comment]
First!

**Comment by llkats** [comment]
Also yes I will be there to offer my mentorship, such as it is. 🙌

**Comment by jedireza** [comment]
I'd be happy give up my spot as a mentor for another first-time/new-ish mentor. I'll still come and help out. I can take out the trash and help with ordering food or anything else really :stuck_out_tongue_winking_eye:

**Comment by Trott** [comment]
I'd like to mentor. Or be the hype person.

**Comment by isaacs** [comment]
Confirmed.

**Comment by isaacs** [comment]
@llkats If you can get on the wifi, install node/npm, look up docs, know literally any JavaScript at all, or even just run around finding people who are stuck and connecting them with other mentors, you'll be able to help people a lot.

**Comment by smallhaxe** [comment]
Can't wait!

**Comment by LindsayElia** [comment]
Would love to help out or just hang out if there are too many mentors. Would like to check out the npm space! Please count me in for mentoring if needed. Thanks.

**Comment by smallhaxe** [comment]
i.e. I'd like to be a mentor, if they're still needed...

Woo!

**Comment by upekabee** [comment]
@Fauntleroy Are you still looking for mentors? If so, I can help!
CC: @negomi

**Comment by bengl** [comment]
I'm in.

**Comment by negomi** [comment]
@upekabee This is the second Saturday of http://www.codeed.org/ :cat: 

Otherwise I'd be up for it!

**Comment by upekabee** [comment]
Oh that's right, @negomi . If @Fauntleroy doesn't mind, I can drive us over afterwards. We'll be a little late.

**Comment by Trott** [comment]
Turns out I can't make it so someone else will have to be the hype person.

@jedireza, let me know if you need me to get the stickers to someone else!

**Comment by negomi** [comment]
I'm in :+1:

**Comment by Fauntleroy** [comment]
@smallhaxe @LindsayElia Woo! Y'all are great!

@upekabee @negomi Having you both there will make an awesome event even more awesome, thanks!

@bengl ✨👍👍💻💯✨

**Comment by jedireza** [comment]
Fellow mentors, it's T-9days until the event. If you're willing, let's spread the news around the bay and let people know about the upcoming event.

Not feeling creative? Here's a couple tweets for inspiration:

 - https://twitter.com/jedireza/status/662030930182144000
 - https://twitter.com/nodeschoolsf/status/661762864936456192

Be sure to link people to the Oakland chapter website: http://nodeschool.io/oakland/

**Comment by Fauntleroy** [comment]
What he said, ALSO:

If anyone has connections with outreach organizations like http://www.railsbridge.org/, http://railsgirls.com/, http://www.pyladies.com/, http://www.youthuprising.org/, http://www.blackgirlscode.com/, etc etc I'd love it if you could reach out and tell them about NodeSchool. I'm always looking to bring new people to these events—especially from underrepresented and underserved communities.

**Comment by substack** [comment]
I can mentor if you need more mentorfolk.

**Comment by Shinobi881** [comment]
I'd like to mentor as well. This is awesome!

**Comment by Fauntleroy** [comment]
@substack @Shinobi881 Feel free to drop by and help some learners!

**Comment by Fauntleroy** [comment]
Thanks, everyone! The event was a huge success due to your hard work. It was really refreshing to see everyone come out and help out our learners.

Also thanks to @isaacs and npm who provided the lovely space and pizza :pizza:!

We won't be having a December event, so rest up and get ready for January!

**Comment by jedireza** [comment]
:raised_hands:

**Comment by isurfbecause** [comment]
:+1: Thanks @isaacs and @Fauntleroy for the support. Can't wait for January!!
