### ISSUE TITLE
January Event

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#18]
I know it's early, but I want to ensure that everything is set for the next event. Currently I'm thinking this:

- Location: **npm**
- Date/Time: **January 16th, 1-5PM** (2 weeks before @nodeschool/sanfrancisco)

Here's a checklist of things I need to remember to do for the next event:

##### Event checklist

- [x] Confirm date and time with venue
- [x] Print stickers
- [x] Wrangle mentors
- [x] Create ti.to event
- [x] Update website
- [x] Add event to nodeschool.io calendar
- [x] Promote event on Twitter
- [x] Ask mentors to help promote
- [x] Reach out to potential promotion partners
- [x] Deliver list of attendees to venue
- [ ] Get nametags, snacks, supplies
- [x] Pre-event confirmation with venue host (day before & day of).
- [x] Get guest WiFi credentials

##### Day of Event

- [x] Send out social media reminders about event
- [x] Arrive early and ensure everything is in order
- [x] Set up check in/greet/sticker area
- [x] Set up refreshments
- [ ] Put up wayfinding signs
- [x] Give opening speech
- [x] Order Pizza
- [ ] Take group photo
- [ ] Clean up event
- [ ] Mentor appreciation happy hour :beers:

**Comment by jedireza** [comment]
Great checklist :+1: 

> Date/Time: 1-5PM, 2 weeks before @nodeschool/sanfrancisco (1/17?)

Did you mean the 16th of January?

**Comment by Fauntleroy** [comment]
Looks like I do! Provided y'all are still taking the last weekend of the month approach.

**Comment by quackingduck** [comment]
:raising_hand: volunteering to be a mentor if it's on the 16th
