### ISSUE TITLE
Mentor Registration for January 16th @ npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#19]
Let's start 2016 off right with another great :tada:NodeSchool:tada:  event! This one's on **Saturday January 16th from 1PM-5PM** at **[npm](https://npmjs.org)**. If you'd like to be one of our volunteer mentors at this event, please leave a comment in this issue!

### Mentors

- [x] @paulgrock
- [x] @Shinobi881
- [x] @isurfbecause 
- [x] @smallhaxe 
- [x] @iarna 
- [x] @JoeDoyle23 
- [x] @daltonamitchell 
- [x] @saposki 
- [x] @phildini 
- [x] @fvntr 

### Organizers

- [x] @fauntleroy

**Comment by noffle** [comment]
Yay nodeschool! I can mentor.

**Comment by paulgrock** [comment]
In

**Comment by Shinobi881** [comment]
Sign me up please.

**Comment by isurfbecause** [comment]
I'm in

**Comment by smallhaxe** [comment]
I'm in, if needed!

**Comment by Fauntleroy** [comment]
@noffle @paulgrock @Shinobi881 @isurfbecause @smallhaxe always glad to have y'all!

**Comment by iarna** [comment]
I'd be happy to mentor =)

**Comment by JoeDoyle23** [comment]
I would be happy to volunteer as a mentor.

**Comment by Fauntleroy** [comment]
@iarna @JoeDoyle23 Welcome to the party! :fireworks:

**Comment by daltonamitchell** [comment]
I'd love to help!

**Comment by saposki** [comment]
will love to help

**Comment by Fauntleroy** [comment]
@daltonamitchell @saposki :hand: Thanks for joining in!

**Comment by Fauntleroy** [comment]
Hey everyone!

We're a bit short on students this time around, so please **spread the word** and try to pull in as many people as possible! The quickest and easiest way to do this would be to Tweet out a [link to our event page](https://ti.to/nodeschool-oakland/nodeschool-oakland-january-npm), or simply [retweet this tweet](https://twitter.com/nodeschooloak/status/686588288560283648).

Anything you can manage would be super appreciated! :confetti_ball: :heart: :confetti_ball:

**Comment by noffle** [comment]
Sorry, could you remove me from the mentor list? I'm not going to be able to make it. :cry:

**Comment by Fauntleroy** [comment]
@noffle can do! Hope to see you next time :wave:

**Comment by phildini** [comment]
@Fauntleroy: Are mentors still wanted? If so, sign me up.

**Comment by fvntr** [comment]
If there is still room for mentors, I'd like to help out.

**Comment by Fauntleroy** [comment]
@phildini @fvntr Y'all will be the last two in the official list! Technically I need to get the venue names sometime this afternoon due to how the front desk security works.

**Comment by phildini** [comment]
Hey @Fauntleroy sorry to be waffley, but there's a chance I won't make it to due to catching the flu. Hoping I feel better tomorrow, but wanted to give a heads-up in case I can't make it.

**Comment by Fauntleroy** [comment]
@phildini that's quite alright, your health should always be your first concern!

**Comment by Fauntleroy** [comment]
I'm excited to see y'all come out this afternoon! Just a few quick reminders:

- The event is from **1-5PM today** at npm (1999 Harrison Street Suite 1150 Oakland, CA 94612)
- Learners will be using [NodeSchool Workshoppers](http://nodeschool.io/#workshoppers) to learn a variety of JS concepts. If you've never done a workshopper before, please take a brief look a few so you'll know what questions to expect.
- As always we'll be following a [Code of Conduct](https://github.com/nodeschool/oakland/blob/master/code-of-conduct.md). If any issues arise, please bring them up with me immediately.
- There will be pizza!!! :pizza: :pizza: :pizza: :pizza: :pizza: :pizza:

**Comment by Fauntleroy** [comment]
Y'all make this event special every ding dang time :100: I'll be back at it again next month, and I hope to see you there!
