### ISSUE TITLE
Mentor Registration for the February 20th Event

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#21]
Hey mentors! Our next event will be held at **npm** on **February 20th from 1-5PM**. If you'd like to mentor at this event, please reply to this issue and I'll add you to the list!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

As always, if you have any questions about mentoring (or the event in general) please reach out!

-----

#### Mentors

- [x] @iarna 
- [x] @noffle 
- [x] @JoeDoyle23 
- [x] @azat-co 
- [x] @tedbreen 
- [x] @Shinobi881 
- [x] @fvntr
- [x] @imurchie 
- [x] @isurfbecause 
- [x] @smallhaxe 

#### Organizers and volunteers

- [x] @fauntleroy
- [x] @isaacs

**Comment by iarna** [comment]
I'm up for it again =)

**Comment by Fauntleroy** [comment]
@iarna Woop woop! You're :hash: :one:!

**Comment by noffle** [comment]
Happy to mentor again!

**Comment by JoeDoyle23** [comment]
I would love to mentor again!

**Comment by Fauntleroy** [comment]
Party on @noffle. Party on @JoeDoyle23.

![waynes_pizza](https://cloud.githubusercontent.com/assets/507047/12729134/144aec70-c8da-11e5-84aa-7e7f1192be12.gif)

**Comment by jedireza** [comment]
![branding](https://cloud.githubusercontent.com/assets/979929/12729949/2a846c18-c921-11e5-9ea8-e71991f72d7e.gif)

**Comment by azat-co** [comment]
I would like to mentor! Please add me to the list. ;-)

**Comment by azat-co** [comment]
@Fauntleroy I was at a San Francisco event and they had a dedicated room for npm with a presenter. Why don't I present and walk a group through ExpressWorks or MEANWorks (since I wrote them)?

github.com/azat-co/expressworks
github.com/azat-co/meanworks

**Comment by tedbreen** [comment]
I would like to mentor. I have over a year of experience with Node and almost two years of experience with JavaScript.

**Comment by Fauntleroy** [comment]
Hey @azat-co! My focus for NodeSchool Oakland right now is to ensure that events monthly before we consider making changes to the event format (just for simplicity's sake). Once things have settled down and the group is in a nice rhythm we might start looking into things like dedicated sessions. That being said, we can definitely mention expressworks/meanworks during the opening remarks and see if any learners would like to break off into a group and work on that together.

Glad to have you, @tedbreen!

**Comment by azat-co** [comment]
@Fauntleroy yeah, KISS. :+1:

**Comment by Shinobi881** [comment]
Add me please! Thanks!

**Comment by Fauntleroy** [comment]
Glad to have you again, @Shinobi881!

![bro_arms](https://cloud.githubusercontent.com/assets/507047/12824811/ec1699ca-cb27-11e5-814c-1c12d174e17d.gif)

**Comment by fvntr** [comment]
add me as well! I had a great time last month.

**Comment by Fauntleroy** [comment]
Let's have a great time again this month, @fvntr :tada:

**Comment by imurchie** [comment]
I would love to be a mentor!

**Comment by isurfbecause** [comment]
I'm in!

**Comment by Fauntleroy** [comment]
@imurchie @isurfbecause 

![as_you_wish](https://cloud.githubusercontent.com/assets/507047/13015921/b00c342c-d170-11e5-95d4-ef836f2c9668.gif)

**Comment by smallhaxe** [comment]
If you still got space, turns out I can make it!

**Comment by Fauntleroy** [comment]
@smallhaxe there's always room for U... go :+1: :100:

**Comment by llkats** [comment]
![I get it!](https://youtu.be/JohZbbgNzpc)
