### ISSUE TITLE
Mentor Registration April 16th @ npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#24]
Hey mentors! Our next event will be held at **npm** on **April 16th from 1-5PM**. If you'd like to mentor at this event, please reply to this issue and I'll add you to the list!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

As always, if you have any questions about mentoring (or the event in general) please reach out!

-----

#### Mentors

- [x] @Shinobi881 
- [x] @iarna 
- [x] @imurchie 
- [x] @nebrius 
- [x] @wfro 
- [x] @noffle 
- [x] @jzelenkov 
- [x] @ultralame 
- [x] @btamayo 
- [x] @BerkeleyTrue

#### Organizers and volunteers

- [x] @fauntleroy

**Comment by Fauntleroy** [comment]
D-don't leave me alone here!

![anime_phone_nervous_text](https://cloud.githubusercontent.com/assets/507047/14256203/dccd9c6c-fa4c-11e5-801a-a213d3ff74d7.gif)

@smallhaxe @paulgrock @noffle @llkats @jedireza @isurfbecause @imurchie @fvntr @shinobi881@tedbreen @iarna

**Comment by Shinobi881** [comment]
Of course, please add me!

**Comment by paulgrock** [comment]
@fauntleroy I can't make it. Sorry buddy

**Comment by iarna** [comment]
I'm in =)

**Comment by Fauntleroy** [comment]
@Shinobi881 yeee!

![quick_clutch_turn_smile](https://cloud.githubusercontent.com/assets/507047/14256881/d2c9a6cc-fa4f-11e5-9065-4b1ec7c1976a.gif)

@paulgrock  awww :(

![bat_cringe](https://cloud.githubusercontent.com/assets/507047/14256889/daf457ca-fa4f-11e5-91e3-04290e07231a.gif)

@iarna yeee! 🔑 

![vander_dance](https://cloud.githubusercontent.com/assets/507047/14256932/032807fa-fa50-11e5-8b5b-d74ba38516ea.gif)

**Comment by imurchie** [comment]
I'm in!

![thumbsup](https://cloud.githubusercontent.com/assets/2614354/14257053/9da0eefa-fa50-11e5-8da2-9efa0084fc3d.gif)

**Comment by nebrius** [comment]
I'm in too :)

**Comment by Fauntleroy** [comment]
@imurchie 👍 

![heavy_weapons_signature](https://cloud.githubusercontent.com/assets/507047/14262006/2f8f856c-fa68-11e5-80a7-17e3efcf8bd8.gif)

@nebrius 🎊 

![wherein_jake_sparkles_like_a_diamond](https://cloud.githubusercontent.com/assets/507047/14262040/5e21ce12-fa68-11e5-9319-855b0272b4cc.gif)

**Comment by wfro** [comment]
Hihi I'm finally in town for nodeschool!  I'd love to help.

**Comment by Fauntleroy** [comment]
@wfro 

![this_is_so](https://cloud.githubusercontent.com/assets/507047/14267334/669ec4c0-fa84-11e5-9fd3-fcda6098b3da.gif)

**Comment by noffle** [comment]
I'm totally there!

**Comment by Fauntleroy** [comment]
@noffle yissss

![thumb_smile](https://cloud.githubusercontent.com/assets/507047/14290972/10a573ce-fb16-11e5-8d57-31d24020c160.gif)

**Comment by jzelenkov** [comment]
I'm in :tada:

**Comment by Fauntleroy** [comment]
Thanks for joining us @jzelenkov! Just make sure you read up about the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) and check out the [mentor best practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices)!

**Comment by jzelenkov** [comment]
@Fauntleroy awesome! Will do!

**Comment by ultralame** [comment]
Have room for any more mentors? Another first timer here.

**Comment by btamayo** [comment]
Hi! If there's more room, I'd like to volunteer (also my first time)!

**Comment by Fauntleroy** [comment]
@ultralame @btamayo You get to be a mentor, and you get to be a mentor!

![oprah_car](https://cloud.githubusercontent.com/assets/507047/14366878/ca02eec8-fcc9-11e5-8b80-18b521741414.gif)

As always, remember to read up about the core NodeSchool workshoppers and check out the mentor best practices!

**Comment by BerkeleyTrue** [comment]
I'd like to mentor.

**Comment by Fauntleroy** [comment]
@BerkeleyTrue You're IN 👍

**Comment by Fauntleroy** [comment]
Hey mentors! Now's the time when I ask all our mentors to help spread the word about our next event!

A cool Tweet you could retweeter: https://twitter.com/nodeschooloak/status/717822232811057152
The sweet ticket page: https://ti.to/nodeschool-oakland/nodeschool-oakland-april-npm
The NodeSchool Oakland website: http://nodeschool.io/oakland/

Please take a second to help out! There's something new to learn from every mentee!

**Comment by mysterlune** [comment]
i really like the quality of the giffies here ;)

**Comment by dkim1116** [comment]
I'd like to volunteer as well!

**Comment by Fauntleroy** [comment]
Hey @dkim1116, feel free to drop by and chat + 🍕, but I can't guarantee we'll have too many students to get at! You can always try your hand at one of the workshoppers you haven't done yet 👍

**Comment by wfro** [comment]
@Fauntleroy I picked up whatever bug has been ravaging my office, so I have to bow out for today :((((.

**Comment by Fauntleroy** [comment]
@wfro noooooo 😭 Get well soon!

![get_well_soon](https://cloud.githubusercontent.com/assets/507047/14581913/60a5dddc-03ae-11e6-9990-6313984a0d7a.gif)

**Comment by wfro** [comment]
Thanks 😄 .  Have fun y'all.

**Comment by nebrius** [comment]
So I hate to do this, but I've had a few things come up and I can't make it to NodeSchool today 😓 Next time!

**Comment by Fauntleroy** [comment]
@nebrius 

![feels_almost_escaping](https://cloud.githubusercontent.com/assets/507047/14582557/6db1e2be-03bd-11e6-8b8d-fdd9de307724.gif)

**Comment by ultralame** [comment]
Sorry for flaking out, hope you had enough mentors!

**Comment by Fauntleroy** [comment]
@ultralame no worries, everything was awwright!

Thanks for coming out, everyone! See you at the next event!

![anchorjump](https://cloud.githubusercontent.com/assets/507047/14610127/615bbaaa-0541-11e6-8c10-35b6db3e6d91.gif)
