### ISSUE TITLE
NodeSchool @ NodeSummit July 26th

### ISSUE THREAD

**Issue by jedireza** [nodeschool/oakland#28]
❤️ Hey Oakland mentors, you're all welcome to participate in https://github.com/nodeschool/sanfrancisco/issues/150 ❤️

**Comment by Fauntleroy** [comment]
Isn't the normal event on the 23rd, and this on the 26th?

**Comment by jedireza** [comment]
Correct. Our regular event is still going to be on Saturday July 23rd. The event for NodeSummit is a separate event.

**Comment by jedireza** [comment]
Title corrected. Thanks @Fauntleroy.

**Comment by doron2402** [comment]
I know its too late but I would love to join to the next meeting
