### ISSUE TITLE
Mentor Registration for July 16 @ npm

### ISSUE THREAD

**Issue by smallhaxe** [nodeschool/oakland#29]
Hi mentors! Our next event will be held at **npm** on **July 16th from 1-5PM**. Please, reply to this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

If you have any questions about mentoring (or the event in general) please reach out! Replies from organizers might be limited through the holiday weekend, but don't be shy. 👋 

-----

#### Mentors

- [x] @fastestOrange 
- [x] @Shinobi881 
- [x] @BerkeleyTrue 
- [x] @iarna 
- [x] @wfro
- [x] @JoeDoyle23 
- [x] @m14t
- [ ] *you?*

#### Organizers and volunteers

- [ ] @Fauntleroy 
- [x] @smallhaxe

**Comment by fastestOrange** [comment]
I would like to volunteer as mentor.

**Comment by Shinobi881** [comment]
Me please!

**Comment by BlackGuyCoding** [comment]
I have this on my calendar.. I'll confirm if I can be a mentor early next week.

**Comment by Fauntleroy** [comment]
Wooo, @fastestOrange! Thanks for dropping in!

Always great to have you on board @Shinobi881!

**Comment by Fauntleroy** [comment]
I'll be out of town for this event, so it's up to y'all to make @smallhaxe gets all them javascript hugs 💞 !

@iarna @imurchie @nebrius @wfro @noffle @jzelenkov @ultralame @btamayo @paulgrock @noffle @llkats @jedireza @isurfbecause @fvntr @prattsj @saposki

![hug_reuinite](https://cloud.githubusercontent.com/assets/507047/16662896/a3db3ece-442e-11e6-9e5d-277b947aa325.gif)

**Comment by BerkeleyTrue** [comment]
Me!

**Comment by iarna** [comment]
Finally, I can make it again! =)

**Comment by isurfbecause** [comment]
I'm tentative. There's a hackathon on friday and sat that weekend. If I don't like it on friday, I'll be at nodeschool on sat :)

**Comment by smallhaxe** [comment]
Yassss. @BerkeleyTrue and @iarna, y'all are on the roster!

![yasss](https://cloud.githubusercontent.com/assets/1261853/16711002/fc2ad242-45fa-11e6-908f-1a01623e1cf0.gif)

**Comment by smallhaxe** [comment]
@isurfbecause @BlackGuyCoding thanks for trying to make it, and we hope tentative turns out to be affirmative!

![cmon](https://cloud.githubusercontent.com/assets/1261853/16711037/5a957f34-45fc-11e6-9142-e1de09ae6608.gif)

**Comment by smallhaxe** [comment]
We're going to giffing miss you, this month @Fauntleroy! Thank you for extending the word to los mentores!

![comeback](https://cloud.githubusercontent.com/assets/1261853/16711046/4ec5091c-45fd-11e6-941e-dbdfeb93b041.gif)

**Comment by wfro** [comment]
I can make it!

**Comment by prattsj** [comment]
Can't make it this month. Conflicts with a work event I need to attend that day. 😿

Hoping to be able to make the one after that... 🙂

**Comment by smallhaxe** [comment]
@wfro glad you can make it! 😎 

And @prattsj sad you cannot make it this time, but (in case you can get away on a workday 🎉 ) there's also [NodeSummit Day Zero](https://github.com/nodeschool/sanfrancisco/issues/150)!

**Comment by JoeDoyle23** [comment]
I am available if there's still a spot.

**Comment by smallhaxe** [comment]
Oh, there's still a spot. Thanks for joining, @JoeDoyle23! 👊 💥

**Comment by m14t** [comment]
Last month was my first time and super fun. I'm in.

**Comment by smallhaxe** [comment]
Awesome! We'll look forward to seeing you again, @m14t... and again... :wink:

**Comment by fastestOrange** [comment]
So sorry for last minute flake out. Friday funday P1 bugfix now most likely stretching into the weekend. Might be able to swing by around 4pm. Hopefully next time.
