### ISSUE TITLE
Mentor Registration for August 13th @ npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#30]
Hi mentors! Our next event will be held at **npm** on **August 13th from 1-5PM**. Please reply to this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

If you have any questions about mentoring (or the event in general) please reach out! Replies from organizers might be limited through the holiday weekend, but don't be shy. 👋 

-----

#### Mentors

- [x] @paulgrock
- [x] @isurfbecause 
- [x] @Shinobi881 
- [x] @JoeDoyle23 
- [x] @bcoe 
- [x] @BerkeleyTrue 
- [x] @azat-co 
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy 
- [ ] @smallhaxe

**Comment by paulgrock** [comment]
Can I come?

**Comment by smallhaxe** [comment]
Like you even need to ask, @paulgrock 🙌

**Comment by isurfbecause** [comment]
count me in.

**Comment by Fauntleroy** [comment]
@isurfbecause 🎊wooooo!!!🎊

**Comment by Shinobi881** [comment]
Me, me, me!!!

**Comment by JoeDoyle23** [comment]
✋ I would love to help out again.

**Comment by Fauntleroy** [comment]
@Shinobi881 @JoeDoyle23 Thanks for joining up!

**Comment by Fauntleroy** [comment]
Hey everyone, it's that time where I ping everyone about the next event!

@iarna @imurchie @nebrius @wfro @noffle @jzelenkov @ultralame @btamayo @noffle @llkats @jedireza @fvntr @prattsj @saposki @fastestOrange @BlackGuyCoding @BerkeleyTrue @m14t

As always, it'll be awesome if you can drop by, but we always need help spreading the word! https://twitter.com/nodeschooloak/status/761666966402629635

![sonic_youre_too_cool](https://cloud.githubusercontent.com/assets/507047/17450343/8532a3ca-5b14-11e6-8afe-6236a62b2d6f.gif)

**Comment by m14t** [comment]
Unfortunately I'm out of town this weekend, but I'll see you next month!

**Comment by bcoe** [comment]
I would be willing to help.

**Comment by BerkeleyTrue** [comment]
My weekend just cleared. I'll be there with bells on!

**Comment by Fauntleroy** [comment]
Can't wait to see you on Saturday! 😂 @bcoe @BerkeleyTrue 

![dance](https://cloud.githubusercontent.com/assets/507047/17492761/1fd129a2-5d62-11e6-87b7-06475a126d8e.gif)

**Comment by azat-co** [comment]
@Fauntleroy I'll be in town so I can stop by to ~~distract~~ mentor nodeschoolers

**Comment by azat-co** [comment]
@Fauntleroy alternatively, we can do a focused Express or MongoDB session. We did Express one at SF.

**Comment by Fauntleroy** [comment]
Hey @azat-co, we're not planning to do any focused sessions at the next event (or in the near future), but we'll be glad to have you!

**Comment by BerkeleyTrue** [comment]
Sorry y'all, but I'm still recovering from a cold and won't make it tomorrow. Don't want to spread my cooties.

Happy Coding

**Comment by imurchie** [comment]
Any need for another mentor? I'm around and would be happy to drop by.

![Manatee](https://pbs.twimg.com/media/CgfjdmQUsAA1k-v.jpg)

**Comment by Fauntleroy** [comment]
@BerkeleyTrue Sorry you can't make it! `getwellsoon.js`! 😷

@imurchie of course! Drop on by and say hi!

![happy_expression](https://cloud.githubusercontent.com/assets/507047/17641454/4a0928fc-60d5-11e6-9d63-16686f50c8c3.gif)

**Comment by isurfbecause** [comment]
I just woke up with a body aching cold :( I cannot make it today. Maybe @BerkeleyTrue and I caught the same thing...
