### ISSUE TITLE
Mentor Registration for 08 October @ npm

### ISSUE THREAD

**Issue by smallhaxe** [nodeschool/oakland#32]
Hello mentors! Our next event will be held at **npm** on **October 8th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋 

-----

#### Mentors

- [x] @iarna 
- [x] @emilong 
- [x] @JoeDoyle23 
- [x] @paulgrock 
- [x] @wfro
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy 
- [x] @smallhaxe

**Comment by Fauntleroy** [comment]
Hey everyone, it's that time where I ping everyone about the next event!

@iarna @imurchie @nebrius @wfro @noffle @jzelenkov @ultralame @btamayo @noffle @llkats @jedireza @fvntr @prattsj @saposki @fastestOrange @BlackGuyCoding @BerkeleyTrue @m14t @paulgrock @emilong 

As always, it'll be awesome if you can drop by, but we also always need help spreading the word! 
https://twitter.com/nodeschooloak/status/780455757615538176
https://twitter.com/nodeschooloak/status/779372818710409216

![i_heart_u_downey_jr](https://cloud.githubusercontent.com/assets/507047/18847429/16d80872-83df-11e6-91a0-98197b6c7bb7.gif)

**Comment by iarna** [comment]
Hey, I'll be there!

**Comment by JoeDoyle23** [comment]
Sign me up!

**Comment by emilong** [comment]
I'm in! 😸

**Comment by Fauntleroy** [comment]
@iarna @JoeDoyle23 @emilong y'all my heroes

![chibi_crew](https://cloud.githubusercontent.com/assets/507047/18886259/051c760c-84a4-11e6-9ad4-0f4f577e8d61.gif)

**Comment by paulgrock** [comment]
@Fauntleroy @smallhaxe y'all got room for another?

**Comment by Fauntleroy** [comment]
@paulgrock oh there's always room for you

![babycarexcited](https://cloud.githubusercontent.com/assets/507047/19047079/2c86d75e-8955-11e6-9ee9-d6cd2778e816.gif)

**Comment by paulgrock** [comment]
![Yes!](https://bukk.it/yes.gif)

**Comment by wfro** [comment]
✋  I can make it!

**Comment by Fauntleroy** [comment]
@wfro

![geordi_thumb](https://cloud.githubusercontent.com/assets/507047/19048452/362be6e0-895b-11e6-9a86-074ae56ba87a.gif)

**Comment by Fauntleroy** [comment]
Alright mentors, today's the day! See y'all at npm at 1PM!
