### ISSUE TITLE
Mentor Registration: NodeSchool Oakland May 2017 @ npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#49]
Hello mentors! Our next event will be held at **npm** on **May 13th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @thomblake 
- [x] @Zahidul-Islam 
- [x] @BerkeleyTrue 
- [x] @EthanJStark 
- [x] @FrankieFabuloso 
- [x] @paulgrock 
- [x] @johnaleman 
- [x] @sotayamashita 
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [ ] @smallhaxe

**Comment by thomblake** [comment]
I'm in

**Comment by Zahidul-Islam** [comment]
@Fauntleroy I would like to help.

**Comment by BerkeleyTrue** [comment]
I'm down!

**Comment by Fauntleroy** [comment]
@thomblake @Zahidul-Islam @BerkeleyTrue I love y'all! See you then!

![love_our_family](https://cloud.githubusercontent.com/assets/507047/25550439/cc6ace94-2c2d-11e7-8fd4-3e39cb0f2635.gif)

**Comment by EthanJStark** [comment]
I'd love to mentor!

**Comment by FrankieFabuloso** [comment]
I would love to be a mentor! 😄

**Comment by Fauntleroy** [comment]
@EthanJStark @FrankieFabuloso Awwww yaaah! Make sure you've got the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) down and come on by!

![not_a_heart](https://cloud.githubusercontent.com/assets/507047/25816286/737bd938-33d8-11e7-9e19-29ca77ea5781.gif)

**Comment by paulgrock** [comment]
@fauntleroy I'd like to participate please

**Comment by Fauntleroy** [comment]
@paulgrock 

![yes_goof_smile](https://cloud.githubusercontent.com/assets/507047/25860768/772271cc-3497-11e7-955d-9379cf592a32.gif)

**Comment by johnaleman** [comment]
I would like to sign up to be a mentor for the meetup this Saturday (13th)

johnaleman@gmail.com

**Comment by Shinobi881** [comment]
Won't make this one. See you next month.

**Comment by sotayamashita** [comment]
@Fauntleroy Hi, I am a member of Nodeschool Tokyo and I will be there.  Can I sigh up as a Mentor?

**Comment by Fauntleroy** [comment]
@johnaleman Alright, see you on Saturday!

@sotayamashita You sure can! See you this Saturday!

![geordi_thumb](https://cloud.githubusercontent.com/assets/507047/25912904/b8081cec-356d-11e7-8b06-536af98d857d.gif)
