### ISSUE TITLE
Mentor Registration: NodeSchool Oakland August 2017 at npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#55]
Hello mentors! Our next event will be held at **npm** on **August 12th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @paulgrock 
- [x] @amazingandyyy 
- [x] @n0f3
- [x] @noffle 
- [x] @mdotslash 
- [x] @xavi- 
- [x] @Zahidul-Islam 
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [ ] @smallhaxe

**Comment by paulgrock** [comment]
In

**Comment by Fauntleroy** [comment]
@paulgrock you're on the list! 🏆 :1st_place_medal: #first

**Comment by amazingandyyy** [comment]
just heard only one signed up in SFNode, I will try to make it and help. Reply soon.

**Comment by Fauntleroy** [comment]
@amazingandyyy I'll tentatively add you to the list! 👍

**Comment by n0f3** [comment]
I'm in!

**Comment by noffle** [comment]
I haven't seen y'all in a long while -- I'm in! :tada: :pizza:

**Comment by Fauntleroy** [comment]
@n0f3 @noffle Thanks for joining in!

![go_team_venture_starburst](https://user-images.githubusercontent.com/507047/28979319-476b6690-78fe-11e7-84c1-6f03012d23ae.gif)

**Comment by mdotslash** [comment]
I volunteer to be a mentor / help learners google error messages!

**Comment by Fauntleroy** [comment]
@mdotslash welcome to the party! 💯 🎊

**Comment by xavi-** [comment]
I'm interested!

**Comment by Fauntleroy** [comment]
@xavi- we'll see you on the 12th! 👍

**Comment by Fauntleroy** [comment]
@Zahidul-Islam glad to have you, as always!

**Comment by JoeDoyle23** [comment]
Put me down as a "maybe". Still seeing if I'm free.

**Comment by n0f3** [comment]
Might have to leave a bit earlier than five is that ok?

**Comment by Fauntleroy** [comment]
@n0f3 That should be fine
@JoeDoyle23 Hope to see you tomorrow!

**Comment by Fauntleroy** [comment]
Thanks for mentoring everyone!

Be sure to check out the next event on September 16th! https://github.com/nodeschool/oakland/issues/56
