### ISSUE TITLE
Mentor Registration: NodeSchool Oakland September 2017 at npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#56]
Hello mentors! Our next event will be held at **npm** on **September 16th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @Zahidul-Islam 
- [x] @paulgrock 
- [x] @apechimp 
- [x] @nfiniteset 
- [x] @ginnyfahs 
- [x] *you?*
- [x] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [ ] @smallhaxe

**Comment by Zahidul-Islam** [comment]
Count me in.

**Comment by paulgrock** [comment]
I would like to participate

**Comment by amazingandyyy** [comment]
I am out of the town, hope to help next time!

**Comment by Fauntleroy** [comment]
@Zahidul-Islam @paulgrock Y'all are so dope every time!

<img width="234" alt="screen shot 2017-09-02 at 8 56 58 am" src="https://user-images.githubusercontent.com/507047/29996940-b5da9590-8fbc-11e7-8e93-7694c04a1459.png">

@amazingandyyy Have fun, hopefully we'll see ya next time!

**Comment by apechimp** [comment]
I'd like to help out!

**Comment by nfiniteset** [comment]
Hi I'd like to volunteer 👋

**Comment by Fauntleroy** [comment]
@apechimp @nfiniteset See you next week! 😄

**Comment by ginnyfahs** [comment]
I'm available to volunteer this weekend! First-timer and looking forward to it.

**Comment by Fauntleroy** [comment]
@ginnyfahs Thanks for your support! See you on Saturday 👋 👍

**Comment by xakirax** [comment]
I'll be there Saturday!

**Comment by bthesorceror** [comment]
I am new to Oakland and would love to help out.

**Comment by Fauntleroy** [comment]
@xakirax @bthesorceror Y'all are welcome! 🎊 

Everyone: spread the word far and wide, we've got an event this Saturday! https://twitter.com/nodeschooloak/status/908080204827860992

**Comment by Fauntleroy** [comment]
The die is cast! See y'all at the event tomorrow! I'll be arriving around 12:30 to set up, the event starts up at 1, and we do announcements at 1:30!

**Comment by mdotslash** [comment]
Late addition, can I still come through?
