### ISSUE TITLE
Mentor Registration: NodeSchool Oakland October 2017 at npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#57]
Hello mentors! Our next event will be held at **npm** on **October 14th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @sotayamashita 
- [ ] @Zahidul-Islam 
- [ ] @n0f3 
- [x] @r-i-c-h 
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [ ] @smallhaxe

**Comment by sotayamashita** [comment]
I am in

**Comment by Fauntleroy** [comment]
@sotayamashita It'll be awesome to have you with us again!

![haruhi_yay_bat](https://user-images.githubusercontent.com/507047/31058476-172f68ae-a6a9-11e7-8649-bee5da49811e.gif)

**Comment by Zahidul-Islam** [comment]
Count me in

**Comment by Fauntleroy** [comment]
@Zahidul-Islam 

![galifanakis_thumb](https://user-images.githubusercontent.com/507047/31279513-2a502bb8-aa5e-11e7-88f4-0ef96d3c69ad.gif)

**Comment by n0f3** [comment]
Coming to this one!

**Comment by Fauntleroy** [comment]
@n0f3 thanks for your help!

**Comment by Fauntleroy** [comment]
Just a week left! Mentors, if you have it in your hearts to help out some mentees, sign up below!

@mdotslash @bthesorceror @xakirax @ginnyfahs @nfiniteset @apechimp @paulgrock

![pikachu_eevee_high_five](https://user-images.githubusercontent.com/507047/31355735-528dece8-acf0-11e7-8fb4-1fbd4a9984fc.gif)

It would also be **super dope** if I could get a signal boost on these tweets 🙇 

https://twitter.com/nodeschooloak/status/916078215113744384

**Comment by mdotslash** [comment]
I won't be able to make it this time b/c I'm out of town. Eat some pizza for me, please!

**Comment by r-i-c-h** [comment]
Can make it if ya want me - Haven't done learnyounode in its entirety, but I'll review in the next day and a half.

**Comment by Fauntleroy** [comment]
@r-i-c-h sounds good! I'll see you there!

**Comment by n0f3** [comment]
Looks like there's a chance I may not be able to make it tomorrow due to some stuff coming up, I'll see you all there if I can clear it up!

**Comment by Zahidul-Islam** [comment]
![alt text](https://media.giphy.com/media/3ohA2ZD9EkeK2AyfdK/giphy.gif)
Unfortunately I won't be able to make it tomorrow.

**Comment by Fauntleroy** [comment]
@n0f3 @Zahidul-Islam That's alright! Hope to see you next time!

**Comment by Fauntleroy** [comment]
...but if there are any of y'all on the fence please drop by today! We're pretty low on mentors!

**Comment by amazingandyyy** [comment]
I can help today! C yall soon~ cheers~

**Comment by xakirax** [comment]
I can help today as well!
