### ISSUE TITLE
Mentor Registration: NodeSchool Oakland January 2018 at npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#58]
Hello mentors! Our next event will be held at **npm** on **January 6th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @Zahidul-Islam 
- [x] @llkats 
- [x] @joshleichtung
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @paulgrock *
- [ ] @Fauntleroy
- [ ] @smallhaxe

**Comment by Zahidul-Islam** [comment]
count me in.

**Comment by Fauntleroy** [comment]
@Zahidul-Islam you're in! Thanks for being first! 🏆

**Comment by llkats** [comment]
![Pam from the Office raising her hand](https://media1.giphy.com/media/xT77Y0CoGA6Nu24PzW/giphy.gif)

**Comment by Fauntleroy** [comment]
@llkats awww yeeeah!

![bird_fox_dance](https://user-images.githubusercontent.com/507047/34423089-a1a4a598-ebce-11e7-9517-593806d549b7.gif)

**Comment by joshleichtung** [comment]
Registered as an attendee and was going to work through some electives like web-audio, but would be interested in mentoring if there's a need. I've been to 3-4 NodeSchools before.

**Comment by Fauntleroy** [comment]
@joshleichtung I'll put you on the list! Thanks for your support!

**Comment by itsmed** [comment]
<img src="https://media.giphy.com/media/3oz8xVBcPAgP7fjBlu/giphy.gif" />
I'm in :)

**Comment by Zahidul-Islam** [comment]
@Fauntleroy I will be little late today. I am trying to be in npm at 1:30 pm

**Comment by Fauntleroy** [comment]
Thanks for coming out in January! We (accidentally) gave February a miss, but please join us for our March event: https://github.com/nodeschool/oakland/issues/59
