### ISSUE TITLE
Next node school night? 

### ISSUE THREAD

**Issue by ffrancia** [nodeschool/oakland#6]
Hey all, I was wondering if anyone had interest in doing another node school night sometime soon? I specifically appreciated the format where we all got together and worked on our own projects but collaborated as well.

**Comment by ugobelu** [comment]
Any further movement on a January date?

**Comment by whatasunnyday** [comment]
I really enjoyed my first node night. I would also like to know if there's any possible way to do Jan/Feb.

**Comment by maxogden** [comment]
Sorry ya'll, I'm out of town for a while, so someone else will have to take the reigns on organizing! I thought the casual hack night format was really fun

**Comment by ffrancia** [comment]
I agree. I suggest that those who express interest in node night propose some dates and see if it works for others. The ones I suggested back in November got no bites.

**Comment by substack** [comment]
Javascript study group has spontaneously restarted every Thursday at 19:00 at sudoroom if people want to come by and hack for that. It's very informal with no presentations and no format, everybody just works on their own stuff and people help each other answering and asking questions. We have an influx of many new people from [cyber.wizard.institute](http://cyber.wizard.institute) who have been showing up regularly to these events too.

**Comment by ffrancia** [comment]
Great!

**Comment by TheAlphaNerd** [comment]
@substack is this still going on?

**Comment by ffrancia** [comment]
Closing this - even though others also expressed interest in having a node school night, none of those who did proposed any dates.
