### ISSUE TITLE
Mentor Registration: NodeSchool Oakland May 2018 at npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#62]
Hello mentors! Our next event will be held at **npm** on **May 12th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @DoctaCloak 
- [x] @itsmed 
- [x] @hath995 
- [x] @paulgrock 
- [x] @Zahidul-Islam 
- [x] @ianhoffman 
- [x] @dylankb 
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [ ] @smallhaxe

**Comment by DoctaCloak** [comment]
Hi I would love to help out if possible!  😃

**Comment by itsmed** [comment]
<img src="https://media.giphy.com/media/3ohs7I3xs77DJJT5de/giphy.gif" />

**Comment by hath995** [comment]
I'll sign up to be a mentor.

**Comment by paulgrock** [comment]
https://tenor.com/x9Kr.gif

**Comment by Zahidul-Islam** [comment]
Count me in.

**Comment by ianhoffman** [comment]
Hey! I'm interested in mentoring or learning -- not sure which one is more appropriate.

My JS knowledge is solid but out of date. I work on a big webapp all day, lots of jQuery and require.js. I know them well.

On the other hand, the last time I touched ES6, webpack, react or anything like that was around a year ago.

My familiarity with `node` as a backend service is also limited, though I know how it works... I'm much more familiar with django, rails, etc.

Happy to go as either a mentor or a learner -- or possibly both?

**Comment by ianhoffman** [comment]
Cool! You can put me down as a mentor then.

**Comment by dylankb** [comment]
Happy to help if I can!

**Comment by Fauntleroy** [comment]
@dylankb I'll see you there!
