### ISSUE TITLE
Mentor Registration: NodeSchool Oakland June 2018 at npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#63]
Hello mentors! Our next event will be held at **npm** on **June 16th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @hath995 
- [x] @Zahidul-Islam 
- [x] @paulgrock 
- [ ] @austintackaberry 
- [x] @bonkydog 
- [x] @Xabadu 
- [x] @n0f3 
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [ ] @Fauntleroy
- [x] @itsmed

**Comment by hath995** [comment]
I'll sign up.

**Comment by itsmed** [comment]
<img src="https://media.giphy.com/media/xUySTEh41261Ff63NS/giphy.gif" />

**Comment by Fauntleroy** [comment]
@hath995 Thank you for your support!

@itsmed You got this!!!

**Comment by Zahidul-Islam** [comment]
count me in!

**Comment by itsmed** [comment]
@Zahidul-Islam see you there!
<img src="https://media.giphy.com/media/WuZ2Yb29Z3J72/giphy.gif" />

**Comment by paulgrock** [comment]
In

**Comment by itsmed** [comment]
@paulgrock 
<img src="https://media.giphy.com/media/11sBLVxNs7v6WA/giphy.gif" />

**Comment by Fauntleroy** [comment]
@austintackaberry you're in!

If it's your first time mentoring at a NodeSchool event, make sure to look over some of the workshoppers!

**Comment by austintackaberry** [comment]
Great! 😄What do you mean by look over the workshoppers? Like walk around and check to see if anyone needs help?

**Comment by Fauntleroy** [comment]
@austintackaberry just make sure you've done some of the [NodeSchool workshoppers](https://nodeschool.io/#workshopper-list), so you know how they work, just in case people need help with those specifically.

**Comment by bonkydog** [comment]
I would like to mentor. Will review workshoppers.

**Comment by itsmed** [comment]
@bonkydog see you then! As @Fauntleroy mentioned, try to have worked through the core [workshoppers](https://nodeschool.io/#workshopper-list) at least and if you're *new* new, check out the [code of conduct](https://github.com/nodeschool/oakland/blob/master/code-of-conduct.md) as well

**Comment by bonkydog** [comment]
ok!

**Comment by Xabadu** [comment]
Say no more, I'm there 🤘

![punisher-say-no-more](https://user-images.githubusercontent.com/3161019/41251529-0d2f769a-6d6f-11e8-8049-d79b96039ac9.gif)

**Comment by Fauntleroy** [comment]
@Xabadu 

![thanks](https://user-images.githubusercontent.com/507047/41259363-2ba92774-6d88-11e8-98d5-18b84e581caf.gif)

**Comment by itsmed** [comment]
@n0f3 
<img src="https://media.giphy.com/media/y3zaVZEltRKhy/giphy.gif" />

**Comment by austintackaberry** [comment]
Turns out I'm not going to be able to make it  🙁

**Comment by Fauntleroy** [comment]
Thanks for helping out! Our next event is on July 14th! https://github.com/nodeschool/oakland/issues/64
