### ISSUE TITLE
Mentor Registration: NodeSchool Oakland August 2018 at npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#66]
Hello mentors! Our next event will be held at **npm** on **August 11th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @Zahidul-Islam 
- [x] @paulgrock 
- [x] @tauseefk 
- [x] @bonkydog 
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [x] @itsmed

**Comment by Zahidul-Islam** [comment]
I would like to help!

**Comment by Fauntleroy** [comment]
@Zahidul-Islam You're in!

![excited_ghibli_mom](https://user-images.githubusercontent.com/507047/43473625-8897b65a-94a5-11e8-9ae8-daec0f556aea.gif)

**Comment by paulgrock** [comment]
I’m in but might not be able to get there until 2

**Comment by Fauntleroy** [comment]
@paulgrock See you at 2!

![black_knight_clock](https://user-images.githubusercontent.com/507047/43660246-3f65adaa-9713-11e8-8134-c6ab58451b44.gif)

**Comment by tauseefk** [comment]
![Permission to come aboard?](https://78.media.tumblr.com/b3ea12f14e4b014c9f3ab247a4f66a4d/tumblr_pcbw2yUncs1qllxuco1_400.gif)

**Comment by Fauntleroy** [comment]
@tauseefk 

![bats_up](https://user-images.githubusercontent.com/507047/43746896-b65a3162-999b-11e8-8bb1-29e0fe5147cd.gif)

**Comment by Fauntleroy** [comment]
We're a little short on mentors! Any of y'all interested in dropping by?

@mpmckenna8 @bonkydog @zenion @austintackaberry @dylankb @ianhoffman

![gonna_have_fun](https://user-images.githubusercontent.com/507047/43849471-5d669c12-9aea-11e8-868f-286c6721e2eb.gif)

**Comment by Fauntleroy** [comment]
@bonkydog Awww yaaaaah!

![spinspinspinspinspinspin](https://user-images.githubusercontent.com/507047/43862493-bafe4ce8-9b0e-11e8-85e1-90d96ac6031b.gif)

**Comment by itsmed** [comment]
@amazingandyyy 

<img src="https://media.giphy.com/media/29rsFlMw8wLlxOCPH1/giphy.gif" />

**Comment by amazingandyyy** [comment]
I am coming now! Sorry for being late! But I want to see you guys.

**Comment by mosse** [comment]
Totally missed this, but would love to help out next time round. Anything in particular I can do to prepare other than review the workshoppers?

**Comment by Fauntleroy** [comment]
@mosse the next on is September 15th! All you really need to do is be familiar with how the workshoppers work, be ready to help anyone, and be awesome!

https://github.com/nodeschool/oakland/issues/67
