### ISSUE TITLE
Mentor Registration: NodeSchool Oakland September 2018 at npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#67]
Hello mentors! Our next event will be held at **npm** on **September 15th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [ ] @paulgrock 
- [x] @whymarrh 
- [ ] @ayesham 
- [ ] @sixcircuit 
- [x] @Zahidul-Islam 
- [x] @austintackaberry 
- [x] @joebalancio 
- [x] @sadbumblebee 
- [x] @r-i-c-h 
- [x] @diffalot 

#### Organizers and volunteers

- [x] @Fauntleroy
- [x] @itsmed

**Comment by paulgrock** [comment]
I’m in

**Comment by Fauntleroy** [comment]
@paulgrock https://www.youtube.com/watch?v=jorJh8DTMVM&t=1m18s

**Comment by whymarrh** [comment]
Neat, can get in on the list as well? I'd love to help.

**Comment by ayesham** [comment]
Giving back is always satisfying. I’d love to mentor and learn a thing or two myself :)

**Comment by Fauntleroy** [comment]
@whymarrh @ayesham 

Y'all are so inspirational! Added!

![Uploading wherein_jake_sparkles_like_a_diamond.gif…]()

**Comment by sixcircuit** [comment]
I'm in.

**Comment by Fauntleroy** [comment]
@sixcircuit you're in!

![porco_says_yes](https://user-images.githubusercontent.com/507047/45239251-7657b500-b299-11e8-8697-30f08a427782.gif)

**Comment by Zahidul-Islam** [comment]
I am in...

**Comment by austintackaberry** [comment]
Count me in!

**Comment by Fauntleroy** [comment]
@Zahidul-Islam @austintackaberry 

![thank_you_so_much](https://user-images.githubusercontent.com/507047/45308026-66c4b000-b4d5-11e8-98c9-84ef09cb63f6.gif)

**Comment by joebalancio** [comment]
I'd like to be a mentor

**Comment by sadbumblebee** [comment]
I volunteer as tribute

**Comment by Fauntleroy** [comment]
@joebalancio thanks for signing up!

@sadbumblebee 

![let_me_hug](https://user-images.githubusercontent.com/507047/45375648-73670800-b5aa-11e8-905a-602fee81841e.gif)

**Comment by r-i-c-h** [comment]
Down to help, though it looks like you may be good to go?

**Comment by Fauntleroy** [comment]
@r-i-c-h You're still more than welcome to join us! When we have a large number of mentors it gives us an opportunity to network and learn from each other as well 👍

**Comment by diffalot** [comment]
I'd like to be a mentor

**Comment by klequis** [comment]
I would like to mentor one day. Can't at the moment.
I was just telling folks at my meetup today about NodeSchool. I attended once. Put a NodeSchool post out to my Facebook page just now.
Enjoy!

**Comment by Fauntleroy** [comment]
@klequis Thanks for spreading the word—every bit helps! Hope to see you at the next event!

**Comment by tauseefk** [comment]
![](https://media.giphy.com/media/l378lW2iqhYyq1M9W/giphy.gif)
can't make it this time, moving to a new place 😭

**Comment by Fauntleroy** [comment]
@tauseefk We're gonna miss you!

![exasperated_ariel](https://user-images.githubusercontent.com/507047/45573286-014c2880-b821-11e8-9981-df7585ed408f.gif)

**Comment by sixcircuit** [comment]
If you have enough people to mentor, and it won't hurt the learners, I'd like to bow out. Unfortunately, I'm not feeling well.

**Comment by paulgrock** [comment]
@Fauntleroy sorry buddy, I can’t make it today. Sad to miss out

**Comment by ayesham** [comment]
Last minute emergency came up. Won’t be able to make it today but definitely hoping next time.

**Comment by Fauntleroy** [comment]
@sixcircuit @paulgrock @ayesham I'm sorry y'all couldn't make it this time! Let's meet up next month!

![skeletor_escape](https://user-images.githubusercontent.com/507047/45589572-b7287d00-b8dc-11e8-878a-83b8dd59ed7f.gif)
