### ISSUE TITLE
Mentor Registration: NodeSchool Oakland October 2018 at npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#68]
Hello mentors! Our next event will be held at **npm** on **October 20th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @paulgrock
- [x] @tauseefk 
- [x] @Zahidul-Islam 
- [x] @vishwasjois 
- [x] @diffalot 
- [x] @austintackaberry 
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [x] @itsmed

**Comment by Zahidul-Islam** [comment]
Count me in...

**Comment by Fauntleroy** [comment]
@tauseefk @Zahidul-Islam thanks for joining in!

![super_kawaii_smile](https://user-images.githubusercontent.com/507047/46503535-f06b5300-c7df-11e8-8f3b-71041d251359.gif)

**Comment by vishwasjois** [comment]
Please count me in

**Comment by Fauntleroy** [comment]
@vishwasjois You're in!

![galifanakis_thumb](https://user-images.githubusercontent.com/507047/46821121-ba2c5700-cd3c-11e8-8cff-732398b6838d.gif)

**Comment by diffalot** [comment]
I'd like to help out

**Comment by Fauntleroy** [comment]
@diffalot You're in!

![as_you_wish](https://user-images.githubusercontent.com/507047/46961742-4c42a100-d056-11e8-86ca-35df29102789.gif)

**Comment by austintackaberry** [comment]
I AM IN

**Comment by Fauntleroy** [comment]
@austintackaberry YES YOU ARE

![oh_lamp_i_knew_youd_understand](https://user-images.githubusercontent.com/507047/47243798-111ed580-d3a8-11e8-8125-669d8e3ddab5.gif)
