### ISSUE TITLE
Mentor Registration: NodeSchool Oakland November 2018 at npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#69]
Hello mentors! Our next event will be held at **npm** on **November 10th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @elie 
- [x] @austintackaberry 
- [x] @radotreyes 
- [x] @tauseefk 
- [x] @Zahidul-Islam 
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [x] @itsmed

**Comment by paulgrock** [comment]
I can’t make it this time :(

**Comment by elie** [comment]
Hey @Fauntleroy, I'm one of the founders of Rithm School a small bootcamp in SF (we teach Node), I'd love to help out as a mentor!

**Comment by Fauntleroy** [comment]
@elie You're more than welcome! Just take a look at the mentor best practices and I'll see you there.

![youre_welcome](https://user-images.githubusercontent.com/507047/47970914-5a298780-e040-11e8-8c3b-1a19e16f3149.gif)

**Comment by radotreyes** [comment]
Sign me up as a mentor! 🙂

**Comment by Fauntleroy** [comment]
@austintackaberry @radotreyes Thanks for joining in!

![thank_you_bob](https://user-images.githubusercontent.com/507047/48031084-ea7ecf80-e107-11e8-8a02-0e17eb2ece19.gif)

**Comment by tauseefk** [comment]
![Yes!!](https://media.giphy.com/media/3ZZeiFwplAGlLxHNvQ/giphy.gif)

**Comment by Zahidul-Islam** [comment]
Count me in...

**Comment by Fauntleroy** [comment]
@tauseefk @Zahidul-Islam Thanks for signing up!

Registration has been slow this time, so we'll probably be short on attendees. Please boost this tweet!

https://twitter.com/nodeschooloak/status/1060242292714262533
