### ISSUE TITLE
Weekly NodeSchool Experiment

### ISSUE THREAD

**Issue by mikeal** [nodeschool/oakland#7]
Hey everybody,

As some of you may know I now have an event space in Embarcadero Cove/Jingletown (https://www.google.com/maps/place/1035+22nd+Ave,+Oakland,+CA+94606/data=!4m2!3m1!1s0x808f86e71b5b0fb5:0x2ab361412006af98?sa=X&ei=vxsLVaT_D8_0oAT7joCIDg&ved=0CB4Q8gEwAA).

I've been thinking about trying out a new NodeSchool format for 6 weeks as an experiment. Every Tuesday we would have the space open from 3pm to 8pm. From 3pm - 6pm we would spend our time working **on** workshoppers and from 6pm-8pm have more of a standard NodeSchool where people come to work through the lessons.

My hope is that the format can do a better job of moving people from using NodeSchool to creating and editing the workshops. I need a few volunteers that can commit for 6 weeks every Tuesday beginning on March 31st.

/cc @substack @groundwater @bcoe

**Comment by whatasunnyday** [comment]
> From 3pm - 6pm we would spend our time working on workshoppers...

Sorry, I didn't exactly understand what this meant. Did you mean creating/updating the existing node school curriculum?

**Comment by mikeal** [comment]
> Did you mean creating/updating the existing node school curriculum?

Yes, exactly :)

**Comment by bcoe** [comment]
@mikeal I could definitely help out towards the end of the nights -- 5:30ish to 8ish -- it's hard for me to sneak off much earlier than that though..., If things went until 9PM I could show up for more of the evening :+1:

**Comment by juliusakula** [comment]
Hello! I just found out about nodeschool, I'd love to come to the next event, that would be April 14 ? If this event is still happening, I'll see you there at 530! Please let me know if it is cancelled @mikeal. When I get there just knock?

**Comment by mikeal** [comment]
@juliusakula Not happening yet, trying to get enough mentors in to it.

**Comment by smallhaxe** [comment]
nodeschool oakland, let's get some plans together quickly for a http://nodeschool.io/international-day event.

Is anyone available to meet next week / weekend to plan and do some organizer hacking?

Main issue tracker is here: https://github.com/nodeschool/international-day/issues

**Comment by GrahamGIGA** [comment]
How about weekends?

**Comment by GrahamGIGA** [comment]
Did this all die again :-((((((   I'd be happy to help / get involved.

**Comment by Fauntleroy** [comment]
@mikeal Is this still in the works, or should it be closed?

**Comment by mikeal** [comment]
Closed :)
