### ISSUE TITLE
Mentor Registration: NodeSchool Oakland January 2019 at npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#70]
Hello mentors! Our next event will be held at **npm** on **January 19th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @paulgrock 
- [x] @Zahidul-Islam 
- [x] @Xabadu 
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [x] @itsmed

**Comment by paulgrock** [comment]
Can I come?

**Comment by Zahidul-Islam** [comment]
Can I come too 😀?

**Comment by itsmed** [comment]
@paulgrock @Zahidul-Islam 

<img src="https://media.giphy.com/media/n5PQk3BGauAdq/giphy.gif" />

**Comment by Xabadu** [comment]
![](https://media.giphy.com/media/elDp5kom23pKM/giphy.gif)

**Comment by itsmed** [comment]
@Xabadu <img src="https://media.giphy.com/media/l1J9urAfGd3grKV6E/giphy.gif" />
