### ISSUE TITLE
Mentor Registration: NodeSchool Oakland February 2019 at npm

### ISSUE THREAD

**Issue by itsmed** [nodeschool/oakland#72]
Hello mentors! Our next event will be held at **npm** on **February 9th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @Xabadu 
- [x] @dkim1116 
- [x] @tauseefk 
- [x] @r-i-c-h 
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [x] @itsmed

**Comment by Xabadu** [comment]
![](https://media.giphy.com/media/3ohc0Tf0tljNH9jiP6/giphy.gif)

**Comment by dkim1116** [comment]
Sign me up! 

![Alt Text](https://ci3.googleusercontent.com/proxy/9mPjqJgY3NjKgCV6S77CYJYpKZq7YJ0ocJfLeTahm52snJeJJ67OhnmAu8Yk6Mf97MHXMp-QxH_Pdg3WhPCD_u-lrmP3MepJaA=s0-d-e1-ft#https://media.giphy.com/media/12Npcg6S68iWCQ/giphy.gif)

**Comment by Fauntleroy** [comment]
@Xabadu @dkim1116 Y'ALL ARE *IN*

![apeach_trance_dance](https://user-images.githubusercontent.com/507047/52010729-16052200-248b-11e9-9dc8-66a406e8edfa.gif)

**Comment by tauseefk** [comment]
![Meeee!](https://media.giphy.com/media/9AIdDInCI55tENXlP8/giphy.gif)

**Comment by Fauntleroy** [comment]
@tauseefk So many mentors! Gotta keep up!

![ryan_typing_furiously](https://user-images.githubusercontent.com/507047/52017774-39d16380-249d-11e9-8829-2a534f6c4b0f.gif)

**Comment by itsmed** [comment]
Hey folks, anyone available to help mentor this week? 🍕 😎 👍 @elie  @austintackaberry @radotreyes  @Zahidul-Islam @paulgrock  @bonkydog @zenion @kevinsimper 

<img src="https://media.giphy.com/media/10kxE34bJPaUO4/giphy.gif" />

**Comment by paulgrock** [comment]
Sorry, I can’t make it. I’m out of town this weekend

**Comment by kevinsimper** [comment]
@itsmed Wish I could join, a bit far away from Copenhagen sadly 😆

**Comment by itsmed** [comment]
No worries @paulgrock enjoy the time OOT!

Sorry to ping @kevinsimper, went through some old issue to find potential mentors. 🌚

**Comment by kevinsimper** [comment]
> Sorry to ping @kevinsimper, went through some old issue to find potential mentors. 🌚

I am happy to be notified, I will join in April 💛

**Comment by r-i-c-h** [comment]
I can help as a mentor.

**Comment by Fauntleroy** [comment]
@r-i-c-h YOU'RE IN!

![ryan_rave](https://user-images.githubusercontent.com/507047/52310002-b4dfc180-2956-11e9-9258-72bfb949d550.gif)

**Comment by r-i-c-h** [comment]
![yes](https://user-images.githubusercontent.com/19735136/52316021-6c340280-296e-11e9-80ad-ce166d509935.gif)

**Comment by itsmed** [comment]
That was a lot of fun, should have closed this last month :) Thanks all!
