### ISSUE TITLE
Mentor Registration: NodeSchool Oakland May 2019 at npm

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#75]
Hello mentors! Our next event will be held at **npm** on **May 18th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @paulgrock
- [x] @bengl
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [x] @itsmed

**Comment by paulgrock** [comment]
I would like to attend

**Comment by klequis** [comment]
Sadly going to miss this one. Getting a ligament tear in my hip fixed and will be spaced out on pain meds this day. Hopefully see you next time.

**Comment by Fauntleroy** [comment]
@paulgrock it's gonna be you and me, buddy!

![gotenks_fusion](https://user-images.githubusercontent.com/507047/57593625-319fb000-74f1-11e9-9db1-3ee83b80499c.gif)

**Comment by paulgrock** [comment]
We got this!

**Comment by bengl** [comment]
I am suddenly able to mentor today! Do you need the extra help today?

**Comment by itsmed** [comment]
We'd love to have you @bengl !

**Comment by itsmed** [comment]
Thanks for yet another great event, everyone, we hope to see you at the next one on the 15th of June!
