### ISSUE TITLE
 Mentor Registration: NodeSchool Oakland June 2019 at npm

### ISSUE THREAD

**Issue by itsmed** [nodeschool/oakland#76]
Hello mentors! Our next event will be held at **npm** on **June 15th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @Xabadu 
- [x] @ideabrian
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [x] @itsmed

**Comment by Xabadu** [comment]
![](https://media.giphy.com/media/Wozl9UAP6DG9vOotl8/giphy.gif)

**Comment by Zahidul-Islam** [comment]
I am in.

**Comment by ideabrian** [comment]
I'll join as a mentor. See you there.

**Comment by Fauntleroy** [comment]
@Xabadu @ideabrian we'll see you there! Thanks for joining us!
