### ISSUE TITLE
(Re)starting monthly mentoring events

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#8]
I recently checked out a Nodeschool event in SF and was shocked to hear that nothing had happened in the Oakland chapter for a while, so I'd like to start organizing and running monthly mentoring events here.

##### Checklist

- [x] Find a suitable venue (NPM, Pandora, Sudo Room?)
- [x] Find a suitable day & time
- [ ] Get a good number of mentors involved
- [x] Build website/event page
- [ ] Acquire stickers

I've already reached out to @isaacs about hosting the event at **NPM** and he's responded positively (barring some possible complications around a future move). I believe NPM would be an ideal location due to its proximity to BART, the company's inclusive culture, and of course the fact that NPM is an integral part of the Node.js ecosystem.

As for day & time, I'd love to do something like the last Nodeschool SF (a long afternoon event on a weekend, say **12-5PM on a Sunday**), but I'm not sure how well that format works for meetups in Oakland. Barring that, weeknight events after work hours (**6-9PM**) would work as well.

I'm not sure who to reach out to in Oakland about mentorship, but I do know that @mikeal is in the area and has been active with Nodeschool before. My hope is that some of the awesome people at NPM might be able to spare some time for mentorship as well. I also know that some people from the last Nodeschool SF event (like @llkats and https://twitter.com/ugobelu) would be interested in helping out.

I can build and design the website, but I do have a couple questions about the ticketing system. Do all Nodeschool chapters use https://ti.to/ ? What's the process for building these websites?

-----

Any input y'all have would be greatly appreciated! Let's get Nodeschool Oak going again!

**Comment by isaacs** [comment]
Just to put more details around the "future move" issue and npm's commitment:

We're going to be most likely moving to a new and much larger office in August.  This will be a better place for node school events, but while we're moving, no good.  In the meantime, our place at 200 Frank Ogawa is suitable for 20 people or so, and with a bit of warning, we could use the building's shared conference space for up to 50 or so.

**Comment by mikeal** [comment]
You can use my warehouse in Embarcadero Cove. It isn't the most convenient location but it can fit as many people as we can possibly get :)

**Comment by smallhaxe** [comment]
Thanks, for restarting the conversation! I haven't been able to make it out to oaklandjs meetups recently, so being able to discuss here is great. @Fauntleroy, in addition to helping with the website, I can do some recruiting of mentors.

Should we have a mentor event first to plan together in person?

**Comment by llkats** [comment]
Notes from SF: The SF chapter has definitely benefited from the sundry companies in SF proper who are willing to sponsor space, food, desks, and volunteers for us. It's been a nice way to visit a bunch of different companies without putting too much of a burden or commitment on any one space. We've been lucky to be able to plan ahead about a month to each event and schedule space ahead of time. I'm not sure how feasible it is for Oakland, but it did add a little flexibility since we only needed a space to commit to one event at a time.

When we were first organizing, there was a lot of conversation in the repository about all sorts of issues. I'm sort of glad that we didn't schedule any meetings before the first event, we sort of just went ahead and did it (it was extremely successful in large part because of @groundwater's, @agminusthev's, and New Relic's support -- maybe they will know additional peeps to ping for East Bay mentorship). 

OaklandJS also seems an ideal place to recruit mentors, and I know others from SF would jump at the chance to mentor and help out with OaklandJS as well. Trying to think of my other node frands in the East Bay... @bryan-m-hughes, @ajfarkas, @lyzidiamond, @jessepollak would you or anyone you know be interested in getting involved?

Let me know how I can help!

**Comment by bryan-m-hughes** [comment]
Thanks for thinking of me @llkats! Unfortunately I'm completely swamped through late July (at best) and won't have time to help.

@TheAlphaNerd, @Frijol, @emilyrose, @alexglow, @morganrallen (if you're still in town), any of you have any free time and want to help?

**Comment by morganrallen** [comment]
I will be back to reality in late July.

**Comment by Jusdev89** [comment]
We still have the space on 17th and broadway, Oakland. Its still available until December this year. but we can get a few hacks in or whatever. Its right by the bart. Let me know. email: devon@devla.bs

**Comment by ajfarkas** [comment]
I'm definitely interested in helping with organization. I could use some
mentoring myself, so I may not be much help in that arena. I'll ask around
for others who may be interested.

**Comment by smallhaxe** [comment]
@Jusdev89, that seems pretty ideal for a start. I hope to make it to oaklandjs and @sudoroom this week to learn whether there's been any discussion of nodeschool meetups and, if so, where that discussion stands. I imagine some of the good folks from @cyberwizardinstitute would be interested, if it's not already on any agenda.

**Comment by jessepollak** [comment]
I can definitely help out with mentoring, though I don't have the bandwidth right now to really contribute to organizing!

**Comment by Jusdev89** [comment]
So for the spot on 17th broadway, Oakland. Im available anytime. but im not a mentor. but i can open the door whenever.  before we were doing sundayz but its up in the air. let me know

**Comment by whatasunnyday** [comment]
I'm not an OaklandJS or Node School meet up regular but I would be happy to help organize or mentor. I'm one of the organizers for RailsBridge Oakland and we hosted an event at Pandora. They said they would be happy to do more events in the future. I would be happy to reach out.

**Comment by Frijol** [comment]
I can help with something! Not sure what's needed, might be most useful to have some kind of organizer/mentor meeting to figure things out? Also happy to cross-post to my meetup http://www.meetup.com/APIs-to-Electrons if useful

**Comment by Fauntleroy** [comment]
@isaacs What kind of lead time do you need to host at NPM? You told me "a few weeks" before, so at least 3 weeks?

@mikeal It's good to know we've got a place in Jingletown if we need it! 

@Jusdev89 Thanks for keeping the door open! What's this place like? Do you have photos of it?

@whatasunnyday I'd love see if Pandora is interested in hosting a Nodeschool event in the future! If you could reach out to your contacts there that would be awesome!

@Frijol @llkats @ajfarkas @smallhaxe Thanks for the support! I'll be hitting up Oakland.js this Wednesday, and it'd be great to see y'all in person then.

I'd love to have an event in late June, but there's lots of stuff going on then. The 22nd and 23rd are **jQuerySF**, the 27th is going to be a **Nodeschool SF** event, and the next Saturday is **July 4th**.
 That leaves us with a couple viable options: 

- Try an event during the afternoon on **June 20th**. This probably won't be enough time for NPM to prepare, so we'd have to use another venue. On the plus side, the 20th doesn't conflict with anything (as far as I know), and it's a full week away from Nodeschool SF's event.
- Try an after work event during the last week of June, or the week of the 15th. Neither of these are great, since there are possible Warriors games peppered in the week of the 15th, and the last week of June would be really close to Nodeschool SF.

I think an event on the 20th is our best shot this month, but I don't have a problem with putting the next event off until July if necessary.

**Comment by whatasunnyday** [comment]
@Fauntleroy Before I reach out, could you give me a bit more information about the following:

- Any need for financial support
- Any need for food
- Approximate time (starts at X ends at Y)
- Possible day of week
- approx # of attendees
- Any other logistical details know of

**Comment by Jusdev89** [comment]
@Fauntleroy Ill show you when you come to the oakland js, its 3 blocks down.

**Comment by Fauntleroy** [comment]
@whatasunnyday Sure!

- Since I've never run a Nodeschool event before I might need to ask someone like @llkats what the financial concerns of a Nodeschool chapter are. When I was at Nodeschool SF they had food and some stickers. I'm assuming those two things come from sponsorship money, but I'm not sure what that sponsorship looks like quite yet.
- The event should have some sort of food/drink available. I'm assuming the standard pizza/whatever unless someone comes up with something more creative.
- The two possible times I'm thinking of are along these lines: on the weekend 1-5PM. On a weekday 6-9PM.
- Any day of the week is possible right now, but the most likely are Monday, Tuesday, Thursday, Saturday, or Sunday.
- I'm not sure what the attendance of Nodeschool Oak was before, but I'd assume 20-30 for now.
- Seating area, what kind of staff they'll have/need to have on location, if they use Node or have anyone who would like to mentor, etc.

**Comment by GrahamGIGA** [comment]
Talk to Anka at Techliminal on 12th, they have sponsored quite a few tech events.  Let me know what I can do to help.....

**Comment by Fauntleroy** [comment]
Hey everyone!

- After talking to @isaacs and it looks like we'll be having an event **at NPM on the 18th of July**.
- There's now a Twitter account for Nodeschool Oakland ([@nodeschooloak](https://twitter.com/nodeschooloak)), which will be used in much the same manner as [@nodeschoolsf](https://twitter.com/nodeschoolsf)
- I'm waiting to hear back on attendee numbers, but once I do I'll put up a signup page and start advertising the event.

Can't wait to get started!

**Comment by GrahamGIGA** [comment]
Great news!

Please send email as well tough, it’s too easy to miss a tweet.

Cheers

G


________________________________
GIGAmacro
Exploring Small Things in a Big Way
c:  +1 415 999 3106
e:  graham@gigamacro.com
 t:  giga_macro
w:  www.gigamacro.com
________________________________

**Comment by mikeal** [comment]
Can you tweet something from that account so that I can re-tweet it :)

**Comment by GrahamGIGA** [comment]
Done, tweets form enigma consult and gigamacro.

Cheers

**Comment by mikeal** [comment]
I meant a tweet from @nodeschooloak :)

**Comment by Fauntleroy** [comment]
@mikeal A tweet now exists: https://twitter.com/nodeschooloak/status/618859774222974976

@GrahamGIGA Where would you like me to send an email to?

**Comment by Jusdev89** [comment]
Sweet can't wait. Thanks.

**Comment by GrahamGIGA** [comment]
No, it’s not my account……..

**Comment by Fauntleroy** [comment]
How does one attain push access for this repo? I'd like to do a couple things:

- Get a [code of conduct](https://github.com/nodeschool/organizers/wiki/Code-of-Conduct-Creation) up ASAP
- Build out a website for the Oakland chapter (just a short blurb and "next event" listing for now)

@maxogden @mikeal do y'all have access? Do I need to consult someone from the Nodeschool org?

**Comment by mikeal** [comment]
@Fauntleroy added.

**Comment by Fauntleroy** [comment]
:+1: @mikeal

**Comment by Fauntleroy** [comment]
@mikeal Do you also have access to ti.io? My email address is the.kaempfer@gmail.com

**Comment by mikeal** [comment]
@Fauntleroy invited :)

**Comment by Fauntleroy** [comment]
The tweet is now up: https://twitter.com/nodeschooloak/status/619163351428431873

**Comment by Fauntleroy** [comment]
Our July event was a huge success! Lots of happy learners and mentors:

![nodeschool-group-photo-for-tweeter](https://cloud.githubusercontent.com/assets/507047/8767198/79e00c26-2e09-11e5-9019-f9f38cd02ac7.jpg)
