### ISSUE TITLE
Mentor Registration: NodeSchool Oakland February 2020 at The Port Workspaces

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#84]
Hello mentors! Our next event will be held at **The Port Workspaces** on **February 15th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [x] @klequis 
- [x] @Xabadu 
- [x] @ckingbailey
- [x] @mr2025
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [x] @Fauntleroy
- [x] @Zahidul-Islam

**Comment by klequis** [comment]
Yeah, looking forward to it!

I'm in.

**Comment by Fauntleroy** [comment]
@klequis awwww yas

![ryan_glowsticks](https://user-images.githubusercontent.com/507047/73582153-d1ff8100-4440-11ea-805e-545140c1e1c0.gif)

**Comment by Xabadu** [comment]
![](https://media1.giphy.com/media/l2YWnHB3QVrgebfsQ/giphy.gif)

**Comment by ckingbailey** [comment]
![torn](https://user-images.githubusercontent.com/20404311/73991208-6023ad80-4900-11ea-9915-2794668ecbcd.gif)

I am not torn. I am enthusiastically volunteering. This gif just happened to be on my desktop atm.

I am, however, all out of faith. This is how I feel.

**Comment by klequis** [comment]
Posted to my Facebook coding group

https://www.facebook.com/groups/free.code.camp.sanramon/

Feel free to post future events there.

**Comment by Fauntleroy** [comment]
@ckingbailey Thanks for signing up!

![i_heart_u_downey_jr](https://user-images.githubusercontent.com/507047/74178728-edad1900-4bf0-11ea-80b1-8cb70da2febf.gif)

@klequis Thanks for the post! Any promotion helps!

**Comment by Mr2025** [comment]
Happy to volunteer

**Comment by Fauntleroy** [comment]
![haruhi_yay_bat](https://user-images.githubusercontent.com/507047/74595073-449c5f00-4ff2-11ea-8388-a2db3e4a6f8b.gif)

@Mr2025 Thanks for doing the thing!

**Comment by ckingbailey** [comment]
Thanks @Fauntleroy for another great Nodeschool. Glad to have it back!

**Comment by Fauntleroy** [comment]
Thanks for coming by everyone, y'all are my heroes!
